### ISSUE TITLE
Network Error Uncaught runtime errors

### ISSUE THREAD

**Issue by Blason** [dev-lu/osint_toolkit#10]
Hi,

I complied using docker and it successfully got compiled however when I am accessing using browser it shows

ERROR
Network Error
ERROR
Network Error
ERROR
Network Error
ERROR
Network Error

**Comment by dev-lu** [comment]
I assume you deployed the app on a remote machine like a Raspberry Pi. Did you modify the Docker Compose file and set the address where the application is deployed on?

**Comment by 0x4hm3d** [comment]
Hello
Same error and I changed the line in the docker compose file before deploying and got the same issue
environment:
      - BACKEND_URL=http://machine-ip:3000 # Backend URL without trailing slash

**Comment by 0x4hm3d** [comment]
Also after seeing the docker-compose logs, everything was successful.
Compiled successfully!
frontend  |
frontend  | You can now view osint-toolkit in the browser.
frontend  |
frontend  |   Local:            http://localhost:3000
frontend  |   On Your Network:  http://172.18.0.3:3000
frontend  |
frontend  | Note that the development build is not optimized.
frontend  | To create a production build, use npm run build.
frontend  |
frontend  | webpack compiled successfully

Thanks

**Comment by dev-lu** [comment]
As you can see in the Docker logs, the frontend runs on port 3000. The backend runs on port 8000 by default, so you should change the port in your compose file to 8000.

**Comment by 0x4hm3d** [comment]
Change the port and the same error, Network Error in the UI
    environment:
      - BACKEND_URL=http://machie-ip:8000 # Backend URL without trailing slash

**Comment by dev-lu** [comment]
Check out your browser console to see where the frontend is trying to connect to.

**Comment by 0x4hm3d** [comment]
Check and found try to open localhost:3000, not the machine-ip:3000, how to change it with the machine-ip
http://localhost:8000/api/apikeys/is_active net::ERR_BLOCKED_BY_CLIENT
Thanks

**Comment by dev-lu** [comment]
Your Docker Compose file should look like this:

```yaml
version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://<IP_ADDRESS>:8000
    stdin_open: true
    tty: true
```

Maybe it helps to to use docker prune command, to delete old data.
