### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by Blason** [dev-lu/osint_toolkit#11]
Hi

Followed the other thread and chagned my docker-compose file as suggested but I am still getting the same error. So the IP that needs to be entered should be a localhost or host IP will do?

root@connector:/opt/osint_toolkit# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.5.116/24 brd 192.168.5.255 scope global ens33
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
5: vti1@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1380 qdisc noqueue state UNKNOWN group default
    inet 192.168.5.116/32 scope global vti1
       valid_lft forever preferred_lft forever
6: vti0@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1380 qdisc noqueue state UNKNOWN group default
    inet 192.168.5.116/32 scope global vti0
       valid_lft forever preferred_lft forever
34: br-da6f0da198b6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    inet 172.21.0.1/16 brd 172.21.255.255 scope global br-da6f0da198b6
       valid_lft forever preferred_lft forever.

version: "3.3"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://192.168.5.116:8000 # Backend URL without trailing slash
    stdin_open: true
    tty: true

**Comment by Blason** [comment]
No luck even with 

root@connector:/opt/osint_toolkit# more docker-compose.yaml
version: "3.3"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://localhost:8000 # Backend URL without trailing slash
    stdin_open: true
    tty: true

**Comment by dev-lu** [comment]
Please try the following compose file:

```yaml
version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://192.168.5.116:8000  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

```
