### ISSUE TITLE
Network Error : Uncaught runtime errors:

### ISSUE THREAD

**Issue by ShakeelPK** [dev-lu/osint_toolkit#14]
I'm trying to run this tool on docker after everything is up and trying to access 3000 port its show me error. ScreenShot Attached

Waiting for your response

![Capture](https://github.com/dev-lu/osint_toolkit/assets/83941561/868b7568-b77f-43e0-9e86-6d14f601a104)

**Comment by ShakeelPK** [comment]
Docker status
![Capture](https://github.com/dev-lu/osint_toolkit/assets/83941561/ececb859-097b-4f49-a633-405d276cbfa5)

**Comment by dev-lu** [comment]
Did you install the app on a remote host? If yes you need to set the IP address of your host in the Docker Compose file.

**Comment by ShakeelPK** [comment]
It's install on my virtual machine which is contacted via bridged network. Can you please tell me were i need to write the ip address in docker-compose file? 

Is this right place to add my machine ip and if yes then i need to write the backend port address ?
![Capture](https://github.com/dev-lu/osint_toolkit/assets/83941561/4a063aa4-37c1-403b-a14e-02bc05636d0b)

**Comment by dev-lu** [comment]
This is an old version of the Compose file. Please clone the latest version of the repository and uncomment the following lines:
```yaml
      #args:
      #  - BACKEND_URL=http://<IP_ADDRESS>:<PORT>  # Backend URL without trailing slash
```

**Comment by ShakeelPK** [comment]
I believe I'm doing mistake can you please help out to identify the problem because I'm getting same error after enter the my virtual machine ip

![Screenshot 2023-08-01 at 11 58 34 PM](https://github.com/dev-lu/osint_toolkit/assets/83941561/b5e82c79-3cdf-43e1-9fd8-a7ace5c0c175)

**Comment by dev-lu** [comment]
You are using an old version with a bug when deploying to a remote machine. Please download the latest version and use this as your compose file:

```yaml
version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://192.168.1.24:8000  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
```
