### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by meetgyn** [dev-lu/osint_toolkit#34]
Help Please

![image](https://github.com/dev-lu/osint_toolkit/assets/3695608/52593fdf-33af-4708-9b93-9c49759f33ce)
![image](https://github.com/dev-lu/osint_toolkit/assets/3695608/d58ccd01-7491-4a91-a9c9-8860d9b6999c)

**Comment by dev-lu** [comment]
Hello meetgyn,

The issue was caused by an error when using newer versions of Python with an older version of Pydantic. I've updated the requirements, so it should work now. Please clone the latest version of the repository and run `docker compose build` to rebuild the image.

Additionally, your compose file needs some adjustments. Based on your configuration, it should look like this:
```yaml
version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8010:8000"
    volumes:
      - ./data:/backend/database/data
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: http://localhost:8010  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
```
