### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by ryangar888** [dev-lu/osint_toolkit#4]
Hi dev,
I tried run with docker compose, then i access the IP:3000 and get this error:
![image](https://github.com/dev-lu/osint_toolkit/assets/124960502/0f922e47-8f56-4638-8023-d9e661038187)

**Comment by dev-lu** [comment]
The error occurs when attempting to access the app from a remote address. Since there is currently no authentication in place, I suggest running it from localhost. However, if you still wish to use the app from a location other than localhost, such as when running it on a Raspberry Pi, I have implemented an update that allows you to configure CORS origins in the Docker Compose file. For example, you can use "ALLOWED_ORIGINS=*" to enable access from any location.

**Comment by hasamba** [comment]
i also have the same problem,
i tried allowed origins=* - didnt work
also tried to add it under frontadd  - didnt work

can you please post a working docker-compose.yaml?
thanks

**Comment by dev-lu** [comment]
Try this one with the latest files from the repository. I tested it a couple minutes ago on a Raspberry Pi and it worked for me.

```yaml
version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://<IP_ADDRESS>:8000 # Backend URL without trailing slash
    stdin_open: true
    tty: true
```
